api/urls.py
from django.contrib import admin
from django.urls import path , include


from .views import      StoreListView   \
                    ,   StoreDetailView \
                    ,   StoreCreateView \
                    ,   StoreUpdateView \
                    ,   StoreDeleteView

app_name = "store"

urlpatterns = [
    path("", StoreListView.as_view(), name="all"),
    path("create/", StoreCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", StoreDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", StoreUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", StoreDeleteView.as_view(), name="delete")

]

# routers

from .router import router

urlpatterns += router.urls

bemarking/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", IndexPage.as_view(), name="index"),
    path("store/", include("api.urls")),

]

api/models.py
from django.db import models
from django.db.models import Model

# Create your models here.

class Store(Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model

    """
    nombre  =  models.CharField(max_length=100, default="Coloque nombre empresa")
    contacto  = models.EmailField(
        blank=False, null=False, default="Coloque gmail de contacto"
        )
    ubicacion  = models.CharField(max_length=150, blank=True, null=True, default="Coloque ubicacion empresa")
    fecha_habilitacion =models.DateField(auto_now=True)

    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase

    class Meta:
       db_table = "tiendas_buenos_aires"


    def __str__(self):
        return f"La empresa: {self.nombre}, ubicada en {self.ubicacion}"

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

# -> paso siguiente -> admin.py

api/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView


from .models import Store

# Create your views here.


class StoreBaseView(View):
    template_name = 'store.html'
    model = Store
    fields = '__all__'
    success_url = reverse_lazy('store:all')


class StoreListView(StoreBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LAS EMPRESAS
    """

class StoreDetailView(StoreBaseView,DetailView):
    template_name = "store_detail.html"

class StoreCreateView(StoreBaseView,CreateView):
    template_name = "store_create.html"
    extra_context = {
        "tipo": "Crear empresa"
    }


class StoreUpdateView(StoreBaseView,UpdateView):
    template_name = "store_create.html"
    extra_context = {
        "tipo": "Actualizar empresa"
    }

class StoreDeleteView(StoreBaseView,DeleteView):
    template_name = "store_delete.html"
    extra_context = {
        "tipo": "Borrar empresa"
    }

bemarking/views.py
from django.views.generic import TemplateView

class IndexPage(TemplateView):
    template_name = "index.html"

api/templates/store.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Bemarking</title>
        <link rel="shortcut icon" href="{% static 'assets/img/icono.png' %}" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
        <link rel="stylesheet" href="{% static 'assets/fontawesome-free-6.4.2-web/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'CSS/1-header.css' %}">
        <link rel="stylesheet" href="{% static 'CSS/8-api_proyecto.css' %}">
        <script  src="{% static 'JS/index.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.32/dist/sweetalert2.all.min.js"></script>
        <script type="text/javascript" src="{% static 'JS/store.js' %}"></script>
        <script src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"></script>
        
    </head> 
    <body class="body_store">
        <!-- Preloader -->
        <div id="preloader">
            <div id="loader"></div>
        </div>
        <main>
            <header id="inicio" class="header1">
                <div class="menu">
                    <a href="{% url 'index' %}" class="logo container">Bemarking</a>
                    <input type="checkbox" id="menu">
                    <label for="menu">
                        <img src="{% static 'assets/img/menu.png' %}" alt="" class="menu-icono">
                    </label>
                    <nav class="navbar container">
                        <ul>
                            <li><a href="{% url 'index' %}"  class="enlaces-menu">Inicio</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Producto</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Servicios</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Contacto</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Empresas</a></li>
                        </ul>
                    </nav>
                </div>
            </header>
            <section class="stoy">
                <div class="store1">
                    <h1>Empresas que trabajan con nosotros</h1>
                    <div class="store_texto1">
                        <p>En el dinámico mundo de los negocios, la presencia en línea y las estrategias de marketing digital son cruciales para el éxito continuo de cualquier empresa. En Bemarking, entendemos la importancia de destacar en el vasto paisaje digital y nos enorgullece ofrecer soluciones integrales que impulsan la visibilidad y el crecimiento de las empresas.</p>
    
                        <h2>¿Por qué elegir Bemarking?</h2>
    
                        <ul>
                            <li><strong>Experiencia y Expertise:</strong> Bemarking se distingue por su profundo conocimiento y experiencia en el ámbito del marketing digital.</li>
                            <li><strong>Enfoque Personalizado:</strong> Adoptamos un enfoque personalizado para cada cliente, trabajando estrechamente para comprender tus metas comerciales.</li>
                            <li><strong>Soluciones Integrales:</strong> Ofrecemos un conjunto completo de servicios de marketing digital, desde SEO hasta desarrollo web.</li>
                            <li><strong>Resultados Medibles:</strong> Creemos en la transparencia y la rendición de cuentas, implementando herramientas analíticas avanzadas.</li>
                            <li><strong>Colaboración a Largo Plazo:</strong> Estamos comprometidos a construir relaciones sólidas y a largo plazo con nuestros clientes.</li>
                        </ul>
                    </div>


                    <h2><a href="{% url 'store:create' %}">Agregar una empresa</a></h2>
                </div>
                <div class="list1">
                    {% for store in store_list %}
                        <div class="list12">
                            <legend>Nombre: {{store.nombre}}</legend>
                            <ul>
                                <li>Direccion de la empresa : {{store.ubicacion}}</li>
                                <li>Contacto : {{store.contacto}}</li>
                                <li>Fecha de alta : {{store.fecha_habilitacion}}</li>
                            </ul>
                            <div>
                                <label for="">Detalles: </label>
                                <a href="{% url 'store:detail' store.id %}">+INFO</a>
                            </div>
                            <div>
                                <label for="">Borrar: </label>
                                <a href="{% url 'store:delete' store.id %}">+INFO</a>
                            </div>
                            <div>
                                <label for="">Editar: </label>
                                <a href="{% url 'store:update' store.id %}">+INFO</a>
                            </div> 
                        </div>
                    {% endfor %}
                </div>
            </section>
        </main>

        <section class="footer_store">
            <footer class="footer-distributed">
            
            <section class="footer-caja">
                <div  class="footer-left">
                    <img src="{% static 'assets/img/icono-5.png' %}" alt="">
                    <h3>
                        Marketing <span>Digital</span></h3>
    
                    <p class="footer-links">
                            Elegí mejorar tu empresa con nosotros
                    </p>
                    <p class="footer-company-name">Copyright @ 2023 <strong>Bemarking</strong></p>
                </div>
    
                <div class="footer-center">
                    <div class="footer-text">
                        <i class="fa fa-map-marker"></i>
                        <p>CABA, Gualeguaychú 8456</p>
                    </div>
    
                    <div class="footer-text">
                        <i class="fa fa-phone"></i>
                        <p>+54 2262-367787</p>
                    </div>
    
                    <div class="footer-text">
                        <i class="fa fa-envelope"></i>
                        <p><a href="https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox">bemarking@gmail.com</a></p>
                    </div>
                </div>
    
                <div class="footer-right">
                    <div class="footer-company-about">
                        <span>Sobre nuestra compañía</span>
                        <p>Somos una agencia que se dedica de forma incansable a potenciar empresas desde todos los frentes. Creemos en edificar con compromiso cada una de las acciones que las compañías ponen en nuestras manos para potenciar sus negocios.</p>
                    </div>
                        
                    <!--
                          <div class="footer-icons">
                        <a href="https://www.youtube.com/channel/UCVrn4_qerPoYYTdeYkg2AsQ"><i class="social__icon fa-brands fa-youtube"></i></a>
                        <a href="https://www.linkedin.com/in/nicolás-ferreiro-b3703a293/"><i class="social__icon fa-brands fa-linkedin"></i></a>
                        <a href="https://www.instagram.com/nicoferreiro1/"><i class="social__icon fa-brands fa-instagram"></i></a>
                        <a href="https://www.facebook.com/nicolas.ferreiro.79/"><i class="social__icon fa-brands fa-facebook"></i></a>
                    </div> 
                    -->
                 
                </div>
            </section>

        </footer>
        </section>
        <script src="{% static 'JS/preloader.js' %}"></script>
    </body>
</html>

{% endblock %}

api/templates/store_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Bemarking</title>
        <link rel="shortcut icon" href="{% static './assets/img/icono.png' %}" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
        <link rel="stylesheet" href="{% static '.assets/fontawesome-free-6.4.2-web/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static './CSS/1-header.css' %}">
        <link rel="stylesheet" href="{% static './CSS/8-api_proyecto.css' %}">
        <script src="{% static './JS/index.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.32/dist/sweetalert2.all.min.js"></script>
    </head>
    <body>
        <main>
            <header id="inicio" class="header3">

                <div class="menu">
                    <a href="#inicio" class="logo container">Bemarking</a>
                    <input type="checkbox" id="menu">
                    <label for="menu">
                        <img src="{% static './assets/img/menu.png' %}" alt="" class="menu-icono">
                    </label>
                    <nav class="navbar container">
                        <ul>
                            <li><a href="{% url 'index' %}"  class="enlaces-menu">Inicio</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Producto</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Servicios</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Contacto</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Store</a></li>
                            
                            <li><a href="https://www.youtube.com/channel/UCVrn4_qerPoYYTdeYkg2AsQ" class="redes-menu"><i class="social__icon fa-brands fa-youtube"></i></a></li>
                            <li><a href="https://www.linkedin.com/in/nicolás-ferreiro-b3703a293/" class="redes-menu"><i class="social__icon fa-brands fa-linkedin"></i></a></li>
                            <li><a href="https://www.instagram.com/nicoferreiro1/" class="redes-menu"><i class="social__icon fa-brands fa-instagram"></i></a></li>
                            <li><a href="https://www.facebook.com/nicolas.ferreiro.79/" class="redes-menu"><i class="social__icon fa-brands fa-facebook"></i></a></li>
                        </ul>
                    </nav>
                </div>

            </header>
            
            <section class="store_create">
                <div class="creat">
                    <form method="post">
                        {% csrf_token %}
                        {{form.as_div}}
                        <input type="submit" value="{{ tipo}}" />
                    </form>

                    <a href="{% url 'store:all' %}">Volvamos al inicio</a>
                </div>
            </section>
    </body>
</html>

{% endblock %}

api/templates/store_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Bemarking</title>
        <link rel="shortcut icon" href="{% static './assets/img/icono.png' %}" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
        <link rel="stylesheet" href="{% static '.assets/fontawesome-free-6.4.2-web/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static './CSS/1-header.css' %}">
        <link rel="stylesheet" href="{% static './CSS/8-api_proyecto.css' %}">
        <script  src="{% static './JS/index.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.32/dist/sweetalert2.all.min.js"></script>
    </head>
    <body>
        
        <main>
            <header id="inicio" class="header1">
                <div class="menu">
                    <a href="#inicio" class="logo container">Bemarking</a>
                    <input type="checkbox" id="menu">
                    <label for="menu">
                        <img src="{% static './assets/img/menu.png' %}" alt="" class="menu-icono">
                    </label>
                    <nav class="navbar container">
                        <ul>
                            <li><a href="{% url 'index' %}"  class="enlaces-menu">Inicio</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Producto</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Servicios</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Contacto</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Empresas</a></li>
                            
                        </ul>
                    </nav>
                </div>
            </header>

            <section class="store_delete">
                <div class="delet">
                    <h2>Estas seguro que deseas borrar esta empresa?</h2>
                    <h2>{{store.nombre}}</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" value="{{ tipo}}" />
                    </form>

                    <a href="{% url 'store:all' %}">Cancelar</a>
                </div>
            </section>
        </main>
    </body>
</html>
















{% endblock %}

api/templates/store_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
    <html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Bemarking</title>
        <link rel="shortcut icon" href="{% static './assets/img/icono.png' %}" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
        <link rel="stylesheet" href="{% static '.assets/fontawesome-free-6.4.2-web/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static './CSS/1-header.css' %}">
        <link rel="stylesheet" href="{% static './CSS/8-api_proyecto.css' %}">
        <script  src="{% static './JS/index.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.32/dist/sweetalert2.all.min.js"></script>
    </head>
    <body>

        <main>
            <header id="inicio" class="header1">
                <div class="menu">
                    <a href="#inicio" class="logo container">Bemarking</a>
                    <input type="checkbox" id="menu">
                    <label for="menu">
                        <img src="{% static './assets/img/menu.png' %}" alt="" class="menu-icono">
                    </label>
                    <nav class="navbar container">
                        <ul>
                            <li><a href="{% url 'index' %}"  class="enlaces-menu">Inicio</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Producto</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Servicios</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Contacto</a></li>
                            <li><a href="{% url 'index' %}" class="enlaces-menu">Empresas</a></li>
                            
                        </ul>
                    </nav>
                </div>
            </header>

            <section class="detalles_store">
                <div class="detal">
                    <h1>{{store.nombre}}</h1>
                    {% for label, value in store.get_fields %}
                    <div>
                        <span>{{label | upper}}</span>
                        <span> <b> {{value}} </b></span>
                    </div>

                    {% endfor %}
                    
                    <a href="{% url 'store:all' %}">Ir al inicio</a>
                </div>
            </section>
                
        </main>
        
    </body>
</html>





{% endblock %}